Network:
  epochs: 200
  batch_size: 100
  n_steps: 5
  dataset: "FashionMNIST"
  rule: "TPA"
  data_path: "../../datasets/mnist"
  lr: 0.0002
  back_lr: 0.0002
  loss: "kernel"
  n_class: 10
  desired_count: 5
  undesired_count: 1
  tau_m: 5
  tau_s: 2
  model: "LIF"
  tpa_vcurve: "large_flat"
  saveall: False
  altset: "tpa_test"
  tpa_filler: "avg"
  tpa_vcurve: "large_flat"
  tpa_perturbation: 0.005
  decayrate: 0.00004
  tpa_bw: False
  tpa_bg: False
  alt_tpa: True

Layers:
  hidden_1:
    type: "linear"
    n_inputs: 784
    n_outputs: 400
    weight_scale: 1
    threshold: 1

  hidden_2:
    type: "linear"
    n_inputs: 400
    n_outputs: 400
    weight_scale: 1
    threshold: 1

  output:
    type: "linear"
    n_inputs: 400
    n_outputs: 10
    weight_scale: 1
    threshold: 1
