Network:
  epochs: 300
  batch_size: 100
  n_steps: 5
  dataset: "MNIST"
  rule: "TPA"
  data_path: "./datasets/mnist"
  lr: 0.0005
  back_lr: 0.0001
  loss: "kernel"
  n_class: 10
  desired_count: 4
  undesired_count: 1
  tau_m: 5
  tau_s: 2
  model: "LIF"
  alt: False
  altset: "tpa_test"
  saveall: False
  dfa_genset: "randn"
  decayrate: 0.0001
  tpa_bw: False
  tpa_bg: False
  tpa_vcurve: "large_flat"
  tpa_perturbation: 0.005
  tpa_filler: "avg"
  alt_tpa: True
  # limit_time: 10

Layers:
  linear_0:
    type: "linear"
    n_inputs: 784
    n_outputs: 100
    weight_scale: 1
    threshold: 1

  linear_1:
    type: "linear"
    n_inputs: 100
    n_outputs: 30
    weight_scale: 1
    threshold: 1


  output:
    type: "linear"
    n_inputs: 30
    n_outputs: 10
    weight_scale: 1
    threshold: 1

